/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import java.util.List;
import Process.SinhVien;
import Process.SinhVienBusiness;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PHAN ANH TUAN
 */
public final class frmDanhSachSinhVien extends javax.swing.JFrame {

    /**
     * Creates new form frmDanhSachSinhVien
     */
    public frmDanhSachSinhVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jtfTimKiem = new javax.swing.JTextField();
        jbtTimKiem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtSinhVien = new javax.swing.JTable();
        jbtThem = new javax.swing.JButton();
        jbtSua = new javax.swing.JButton();
        jbtXoa = new javax.swing.JButton();
        jbtDong = new javax.swing.JButton();
        jbtHienThi = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Từ khóa:");

        jbtTimKiem.setText("Tìm kiếm ");
        jbtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtTimKiemActionPerformed(evt);
            }
        });

        jtSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jtSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtSinhVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtSinhVien);

        jbtThem.setText("Thêm");
        jbtThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThemActionPerformed(evt);
            }
        });

        jbtSua.setText("Sửa");
        jbtSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSuaActionPerformed(evt);
            }
        });

        jbtXoa.setText("Xóa");
        jbtXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtXoaActionPerformed(evt);
            }
        });

        jbtDong.setText("Đóng");
        jbtDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDongActionPerformed(evt);
            }
        });

        jbtHienThi.setText("Hiển thị");
        jbtHienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtHienThiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(121, 121, 121)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(jbtTimKiem))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(98, 98, 98)
                            .addComponent(jbtHienThi)
                            .addGap(37, 37, 37)
                            .addComponent(jbtThem)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtSua)
                            .addGap(46, 46, 46)
                            .addComponent(jbtXoa)
                            .addGap(48, 48, 48)
                            .addComponent(jbtDong)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtTimKiem))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSua)
                    .addComponent(jbtXoa)
                    .addComponent(jbtThem)
                    .addComponent(jbtDong)
                    .addComponent(jbtHienThi))
                .addContainerGap(210, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThemActionPerformed
        frmSinhVienAdd frmThemMoi = new frmSinhVienAdd();
        frmThemMoi.setVisible(true);
    }//GEN-LAST:event_jbtThemActionPerformed

    private void jbtSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSuaActionPerformed
        String maSV = "";
        int dongChon = 0;
        frmSinhVienAdd frmSua = new frmSinhVienAdd();
        //lấy chỉ số dòng chọn trên jTable
        dongChon = jtSinhVien.getSelectedRow();
        //lấy thông tin mã sinh viên của dòng chọn
        maSV = "" + jtSinhVien.getValueAt(dongChon, 0);
        //truyền mã sinh viên lên giao diện sửa
        frmSua.setMaSinhVien(maSV);
        //hiển thị thông tin
        frmSua.setVisible(true);
        frmSua.hienThiChiTietSinhVien();
    }//GEN-LAST:event_jbtSuaActionPerformed

    private void jbtXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtXoaActionPerformed
        int ketQua = JOptionPane.showConfirmDialog(rootPane, "ban co chac chan muon xoa thong tin nay?" ,
                "thong bao", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION);
        if(ketQua == JOptionPane.YES_OPTION) {
            //khai báo biến
            String maSV = "";
            int dongChon = 0;
            //lấy chỉ số dòng chọn trên jTable 
            dongChon = jtSinhVien.getSelectedRow();
            //lấy thông tin mã sinh viên của dòng chọn
            maSV = "" + jtSinhVien.getValueAt(dongChon, 0);
            //khai báo đối tượng
            ISinhVien svb = new SinhVienBusiness();
            //thực hiện xóa từ database
            boolean isXoa = svb.xoa(maSV);
            if(isXoa) {
                JOptionPane.showMessageDialog(rootPane, "xoa thanh cong");
                hienThiDanhSachSinhVien();
            }
        }
        
    }//GEN-LAST:event_jbtXoaActionPerformed

    private void jtSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtSinhVienMouseClicked
        
    }//GEN-LAST:event_jtSinhVienMouseClicked

    private void jbtDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDongActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbtDongActionPerformed

    private void jbtHienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtHienThiActionPerformed
        hienThiDanhSachSinhVien();
    }//GEN-LAST:event_jbtHienThiActionPerformed

    private void jbtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtTimKiemActionPerformed
        ISinhVien svb = new SinhVienBusiness();
        List<SinhVien> lstSinhVien = svb.timKiem(jtfTimKiem.getText());
        String colTieuDe[] = new String[] {"Mã SV", "Họ tên", "Giới tính", "Ngày sinh", "Điện thoại", "Email", "Địa chỉ", "Mã khoa"};
        DefaultTableModel dtm = new DefaultTableModel(colTieuDe, 0);
        Object row[];
        for (SinhVien x : lstSinhVien) {
            row = new Object[8];
            row[0] = x.getMaSV();
            row[1] = x.getHoTen();
            row[2] = x.getGioiTinh();
            row[3] = x.getNgaySinh();
            row[4] = x.getDienThoai();
            row[5] = x.getEmail();
            row[6] = x.getDiaChi();
            row[7] = x.getMaKhoa();
            dtm.addRow(row);
        }
        jtSinhVien.setModel(dtm);
    }//GEN-LAST:event_jbtTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void hienThiDanhSachSinhVien() {
        ISinhVien svb = new SinhVienBusiness();
        List<SinhVien> lstSinhVien = svb.layDanhSach();
        String colTieuDe[] = new String[] {"Mã SV", "Họ tên", "Giới tính", "Ngày sinh", "Điện thoại", "Email", "Địa chỉ", "Mã khoa"};
        DefaultTableModel dtm = new DefaultTableModel(colTieuDe, 0);
        Object row[];
        for (SinhVien x : lstSinhVien) {
            row = new Object[8];
            row[0] = x.getMaSV();
            row[1] = x.getHoTen();
            row[2] = x.getGioiTinh();
            row[3] = x.getNgaySinh();
            row[4] = x.getDienThoai();
            row[5] = x.getEmail();
            row[6] = x.getDiaChi();
            row[7] = x.getMaKhoa();
            dtm.addRow(row);
        }
        jtSinhVien.setModel(dtm);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDanhSachSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDanhSachSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDanhSachSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDanhSachSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDanhSachSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtDong;
    private javax.swing.JButton jbtHienThi;
    private javax.swing.JButton jbtSua;
    private javax.swing.JButton jbtThem;
    private javax.swing.JButton jbtTimKiem;
    private javax.swing.JButton jbtXoa;
    private javax.swing.JTable jtSinhVien;
    private javax.swing.JTextField jtfTimKiem;
    // End of variables declaration//GEN-END:variables
}
